name: Super Linter

on:
  workflow_dispatch:
 #push:
 #   branches: [main]

  #pull_request:

jobs:
  build:
    name: Lint Code Base
    
    runs-on: ubuntu-latest

    permissions:
      contents: read
      statuses: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
    
      - name: Lint Code Base
        uses: github/super-linter@v4
        #uses: super-linter/super-linter@v7.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_WORKSPACE: ${{ github.workspace }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          IGNORE_GITIGNORED_FILES: true
